name: Heroku Api 

on:
  push:
    branches:
      - main
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add code-network-api https://heroku:${{ secrets.HEROKU_AUTH_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_API_APP_NAME }}.git
      - name: Deploy backend to Heroku
        run: git push code-network-api `git subtree split --prefix apps/backend main`:refs/heads/main --force