name: Heroku Client 

on:
  push:
    branches:
      - main
    paths:
      - "apps/frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku. 
        uses: gonuit/heroku-docker-deploy@v1.3.3 
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_AUTH_TOKEN }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: dockerfile.frontend
          docker_options: "--no-cache"
          process_type: web